sudo: required
services:
  - docker

before_install:
  - docker build -t selimdincer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true selimdincer/react-test npm test

after_success:
  -  docker build -t selimdincer/multi-client ./client
  -  docker build -t selimdincer/multi-nginx ./nginx
  -  docker build -t selimdincer/multi-server ./server
  -  docker build -t selimdincer/multi-worker ./worker
# Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to the Docker Hub
  - docker push selimdincer/multi-client
  - docker push selimdincer/multi-nginx
  - docker push selimdincer/multi-server
  - docker push selimdincer/multi-worker

deploy:
  provide: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-871834746074
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  


